Parameters:
  VPCId:
    Type: String
    Description: The VPC ID where the security group will be created.

Resources:
  # Create Security Group
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: "AllowSSHAndHTTP"

Outputs:
  SecurityGroupId:
    Value: !Ref SecurityGroup
    Export:
      Name: SecurityGroupId
